/**
 * Keywords canônicas do Digimon Card Game (efeitos delimitados por ＜＞).
 * Extraídas da lista de filtros do app de referência
 * (github.com/TakaOtaku/Digimon-Card-App). Usadas para detectar keywords
 * por substring nos textos de efeito da carta durante a normalização.
 */
export const CANONICAL_KEYWORDS: readonly string[] = [
  '＜Alliance＞',
  '＜Armor Purge＞',
  '＜Ascension＞',
  '＜Barrier＞',
  '＜Blast Digivolve＞',
  '＜Blast DNA Digivolve ([Alphamon] + [Ouryumon])＞',
  '＜Blast DNA Digivolve ([Angewomon] + [LadyDevimon])＞',
  '＜Blast DNA Digivolve ([Breakdramon] + [Slayerdramon])＞',
  '＜Blast DNA Digivolve ([DinoBeemon] + [Paildramon])＞',
  '＜Blast DNA Digivolve ([Durandamon] + [BryweLudramon])＞',
  '＜Blast DNA Digivolve ([Fenriloogamon] + [Kazuchimon])＞',
  '＜Blast DNA Digivolve ([WarGreymon] + [MetalGarurumon])＞',
  '＜Blitz＞',
  '＜Blocker＞',
  '＜Collision＞',
  '＜Decode ([Aegiomon])＞',
  '＜Decode ([Calmaramon])＞',
  '＜Decode (Lv.4 w/[Aqua]/[Sea Animal] in any trait)＞',
  '＜Decode (Lv.5 w/[Aqua]/[Sea Animal] in any trait)＞',
  '＜Decode (Lv.6 or lower w/[Aqua]/[Sea Animal] in any trait)＞',
  '＜Decode ([Lanamon])＞',
  '＜Decode  ([Betamon])/([ModokiBetamon])＞',
  '＜Decoy ([Bagra Army] trait)＞',
  '＜Decoy (Black)＞',
  '＜Decoy (Black/White)＞',
  '＜Decoy (Red/Black)＞',
  '＜Decoy ([D-Brigade] trait)＞',
  '＜Decoy ([Deva] or [Four Sovereigns] trait)＞',
  '＜Decoy ([Puppet] trait)＞',
  '＜De-Digivolve 1＞',
  '＜De-Digivolve 2＞',
  '＜De-Digivolve 3＞',
  '＜De-Digivolve 4＞',
  '＜Delay＞',
  '＜Detach ([Seven Code] trait＞',
  '＜Digi-Burst 1＞',
  '＜Digi-Burst 2＞',
  '＜Digi-Burst 3＞',
  '＜Digi-Burst 4＞',
  '＜Digi-Burst up to 4＞',
  '＜Digisorption -2＞',
  '＜Digisorption -3＞',
  '＜Digisorption＞',
  '＜Draw 1＞',
  '＜Draw 2＞',
  '＜Draw 3＞',
  '＜Engage＞',
  '＜Evade＞',
  '＜Execute＞',
  '＜Fragment (2)＞',
  '＜Fragment (3)＞',
  '＜Guard＞',
  '＜Iceclad＞',
  '＜Fortitude＞',
  '＜Jamming＞',
  '＜Link +1＞',
  '＜Link +2＞',
  '＜Material Save 1＞',
  '＜Material Save 2＞',
  '＜Material Save 3＞',
  '＜Material Save 4＞',
  '＜Mind Link＞',
  '＜Overclock ([Appmon] trait)＞',
  '＜Overclock ([Composite] trait)＞',
  '＜Overclock ([Puppet] trait)＞',
  '＜Overclock ([Unidentified] trait)＞',
  '＜Partition (Blue Lv.4 + Green Lv.4)＞',
  '＜Partition (Black Lv.4 + Yellow Lv.4)＞',
  '＜Partition (Red Lv.4 + Yellow Lv.4)＞',
  '＜Partition (Yellow Lv.6 + Black Lv.6)＞',
  '＜Partition (Yellow/Black Lv.6 + Green/Purple Lv.6)＞',
  '＜Piercing＞',
  '＜Progress＞',
  '＜Raid＞',
  '＜Reboot＞',
  '＜Recovery +1 (Deck)＞',
  '＜Recovery +2 (Deck)＞',
  '＜Retaliation＞',
  '＜Rush＞',
  '＜Save＞',
  '＜Security A. +1＞',
  '＜Security A. +2＞',
  '＜Security A. -1＞',
  '＜Security A. -2＞',
  '＜Security A. -3＞',
  '＜Training＞',
  '＜Vortex＞',
];
